name:   swot
description: Simple Workout Timer
publish_to: 'none'
version: 0.0.1+2

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  audioplayers: ^4.1.0
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: San Francisco
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Regular.otf
    - family: San Francisco Reg
      fonts:
        - asset: assets/fonts/SF-Pro.ttf
    - family: San Fransisco Mono
      fonts:
        - asset: assets/fonts/SF-Mono-Regular-MOD.otf
    - family: SF Light Mono
      fonts:
        - asset: assets/fonts/SF-Mono-Light-MOD.otf
    - family: San Francisco Light
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Light.otf
    - family: San Francisco Num
      fonts:
        - asset: assets/fonts/SFPro-Numbers.otf
  uses-material-design: true

  assets:
    - assets/alarms/countdown_alarm_1.mp3
    
    - assets/alarms/alarm_5.mp3
    